"""empty message

Revision ID: ab9d35a2a7e3
Revises: 
Create Date: 2023-06-15 12:13:08.695553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9d35a2a7e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_riders',
    sa.Column('riderID', sa.Integer(), nullable=False),
    sa.Column('riderName', sa.String(length=20), nullable=False),
    sa.Column('riderSalary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('riderID'),
    sa.UniqueConstraint('riderName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_riders')
    # ### end Alembic commands ###
